const actionTypes = Object.freeze({
  //app
  APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
  SET_CONTENT_OF_CONFIRM_MODAL: "SET_CONTENT_OF_CONFIRM_MODAL",
  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",

  //user
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  PROCESS_LOGOUT: "PROCESS_LOGOUT",

  USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
  USER_REGISTER_FAILED: 'USER_REGISTER_FAILED',

  GET_USER_IMAGE_SUCCESS: 'GET_USER_IMAGE_SUCCESS',
  GET_USER_IMAGE_FAILED: 'GET_USER_IMAGE_SUCCESS',

  //admin
  FETCH_ROLE_START: 'FETCH_ROLE_START',
  FETCH_ROLE_SUCCESS: 'FETCH_ROLE_SUCCESS',
  FETCH_ROLE_FAILED: 'FETCH_ROLE_FAILED',

  CREAT_NEW_ACCOUNT_SUCCESS: 'CREAT_NEW_ACCOUNT_SUCCESS',
  CREAT_NEW_ACCOUNT_FAILED: 'CREAT_NEW_ACCOUNT_FAILED',

  GET_ALL_ACCOUNT_SUCCESS: 'GET_ALL_ACCOUNT_SUCCESS',
  GET_ALL_ACCOUNT_FAILED: 'GET_ALL_ACCOUNT_FAILED',

  DELETE_ACCOUNT_SUCCESS: 'DELETE_ACCOUNT_SUCCESS',
  DELETE_ACCOUNT_FAILED: 'DELETE_ACCOUNT_SUCCESS',
  

  EDIT_ACCOUNT_SUCCESS: 'EDIT_ACCOUNT_SUCCESS',
  EDIT_ACCOUNT_FAILED: 'EDIT_ACCOUNT_FAILED',


});

export default actionTypes;
